In [25]:
import os # 경고 대응
os.environ['OMP_NUM_THREADS'] = '1'

import pandas as pd
import numpy as np

df = pd.read_excel('C:/mypycode/project2/final/cal112_kind_of_average.xlsx')

df = df.drop(['Unnamed: 0'], axis=1) 
df = df[['지역','5대범죄 건수 평균', '인구밀도 평균', '여성 가구원수 평균', 'cctv수 평균', '가로등수 평균', '112신고 건수 평균']]
df

,지역,5대범죄 건수 평균,인구밀도 평균,여성 가구원수 평균,cctv수 평균,가로등수 평균,112신고 건수 평균
0,강남구,7543.571429,6736.714286,261914.571429,869.857143,13837.285714,170421.428571
1,강동구,4163.714286,13509.142857,212260.000000,319.714286,7724.428571,89579.714286
2,강북구,3460.714286,11169.571429,154574.000000,428.428571,4388.285714,74903.428571
3,강서구,4862.000000,18163.000000,287358.857143,323.142857,7849.571429,114848.000000
4,관악구,5372.428571,21519.571429,253621.857143,536.428571,5190.142857,112705.000000
5,광진구,4355.857143,25591.714286,181476.857143,404.571429,4857.142857,86648.571429
6,구로구,4726.428571,22002.714286,212753.428571,429.142857,7669.285714,86006.571429
7,금천구,3160.857143,18462.857143,120722.142857,308.142857,5243.000000,63704.285714
8,노원구,4172.857143,13607.428571,265683.714286,309.142857,9302.285714,89983.428571
9,도봉구,2214.142857,16407.000000,162298.714286,233.285714,4499.000000,54898.857143
10,동대문구,3887.714286,15459.428571,177716.142857,370.571429,8152.285714,28858.428571
11,동작구,3280.285714,16460.857143,199861.571429,244.714286,5542.857143,69205.428571
12,마포구,4892.428571,18313.285714,190437.285714,328.857143,8084.571429,107486.285714
13,서대문구,3051.857143,16220.285714,162843.142857,258.428571,5910.142857,64242.428571
14,서초구,4809.428571,26957.714286,205641.285714,550.285714,12161.285714,98123.571429
15,성동구,2656.285714,14388.142857,147371.142857,458.142857,5860.714286,57321.428571
16,성북구,3175.571429,21849.714286,223697.428571,577.714286,5478.000000,75245.142857
17,송파구,5724.714286,19342.571429,317456.428571,374.714286,13093.428571,127502.571429
18,양천구,3640.285714,16527.714286,219399.571429,444.714286,7816.571429,74413.285714
19,영등포구,5744.857143,24884.285714,195884.142857,426.714286,9287.285714,113342.142857
20,용산구,3441.571429,17499.857143,113818.571429,306.714286,7433.571429,73440.857143
21,은평구,3890.428571,9324.000000,233652.428571,534.000000,6441.285714,86552.285714
22,종로구,3795.857143,14084.571429,77940.714286,100.714286,8887.428571,74265.714286
23,중구,4050.142857,19811.428571,65017.000000,307.571429,8634.428571,128958.714286
24,중랑구,4328.142857,18328.714286,193835.571429,435.000000,5947.142857,87161.000000

In [26]:
df_hot = pd.get_dummies(df2['지역'])
df3 = df.drop('지역', axis=1)
df_hot

,강남구,강동구,강북구,강서구,관악구,광진구,구로구,금천구,노원구,도봉구,...,성동구,성북구,송파구,양천구,영등포구,용산구,은평구,종로구,중구,중랑구
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [38]:
df4 = df_hot.join(df3)
df4

,강남구,강동구,강북구,강서구,관악구,광진구,구로구,금천구,노원구,도봉구,...,은평구,종로구,중구,중랑구,5대범죄 건수 평균,인구밀도 평균,여성 가구원수 평균,cctv수 평균,가로등수 평균,112신고 건수 평균
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,7543.571429,6736.714286,261914.571429,869.857143,13837.285714,170421.428571
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,4163.714286,13509.142857,212260.000000,319.714286,7724.428571,89579.714286
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,3460.714286,11169.571429,154574.000000,428.428571,4388.285714,74903.428571
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,4862.000000,18163.000000,287358.857143,323.142857,7849.571429,114848.000000
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,5372.428571,21519.571429,253621.857143,536.428571,5190.142857,112705.000000
5,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,4355.857143,25591.714286,181476.857143,404.571429,4857.142857,86648.571429
6,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,4726.428571,22002.714286,212753.428571,429.142857,7669.285714,86006.571429
7,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,3160.857143,18462.857143,120722.142857,308.142857,5243.000000,63704.285714
8,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,4172.857143,13607.428571,265683.714286,309.142857,9302.285714,89983.428571
9,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,2214.142857,16407.000000,162298.714286,233.285714,4499.000000,54898.857143
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,3887.714286,15459.428571,177716.142857,370.571429,8152.285714,28858.428571
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,3280.285714,16460.857143,199861.571429,244.714286,5542.857143,69205.428571
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,4892.428571,18313.285714,190437.285714,328.857143,8084.571429,107486.285714
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,3051.857143,16220.285714,162843.142857,258.428571,5910.142857,64242.428571
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,4809.428571,26957.714286,205641.285714,550.285714,12161.285714,98123.571429
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2656.285714,14388.142857,147371.142857,458.142857,5860.714286,57321.428571
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,3175.571429,21849.714286,223697.428571,577.714286,5478.000000,75245.142857
17,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,5724.714286,19342.571429,317456.428571,374.714286,13093.428571,127502.571429
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,3640.285714,16527.714286,219399.571429,444.714286,7816.571429,74413.285714
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,5744.857143,24884.285714,195884.142857,426.714286,9287.285714,113342.142857
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,3441.571429,17499.857143,113818.571429,306.714286,7433.571429,73440.857143
21,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,3890.428571,9324.000000,233652.428571,534.000000,6441.285714,86552.285714
22,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,3795.857143,14084.571429,77940.714286,100.714286,8887.428571,74265.714286
23,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,4050.142857,19811.428571,65017.000000,307.571429,8634.428571,128958.714286
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,4328.142857,18328.714286,193835.571429,435.000000,5947.142857,87161.000000

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(drop='first'),[2] )])

In [ ]:
dataset=df4
X = df4[df4.columns.difference(['112신고 건수 평균'])]
X = dataset.drop(['112신고 건수 평균'], axis=1).values
y = dataset.iloc[:,-1].values

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit_transform(df2['지역'])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
#label encoding

In [10]:
df2['지역_n'] = le.fit_transform(df2['지역'])
df2.head()

C:\Users\user\AppData\Local\Temp\ipykernel_11496\1835579864.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['지역_n'] = le.fit_transform(df2['지역'])

,지역,5대범죄 건수 평균,인구밀도 평균,여성 가구원수 평균,cctv수 평균,가로등수 평균,112신고 건수 평균,지역_n
0,강남구,7543.571429,6736.714286,261914.571429,869.857143,13837.285714,170421.428571,0
1,강동구,4163.714286,13509.142857,212260.000000,319.714286,7724.428571,89579.714286,1
2,강북구,3460.714286,11169.571429,154574.000000,428.428571,4388.285714,74903.428571,2
3,강서구,4862.000000,18163.000000,287358.857143,323.142857,7849.571429,114848.000000,3
4,관악구,5372.428571,21519.571429,253621.857143,536.428571,5190.142857,112705.000000,4

In [11]:
le.classes_

array(['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구',
       '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구',
       '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구'], dtype=object)

In [12]:
le.inverse_transform([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

array(['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구',
       '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구',
       '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구'], dtype=object)

In [14]:
df2['지역'].value_counts()

강남구     1
서대문구    1
중구      1
종로구     1
은평구     1
용산구     1
영등포구    1
양천구     1
송파구     1
성북구     1
성동구     1
서초구     1
마포구     1
강동구     1
동작구     1
동대문구    1
도봉구     1
노원구     1
금천구     1
구로구     1
광진구     1
관악구     1
강서구     1
강북구     1
중랑구     1
Name: 지역, dtype: int64

In [15]:
df2['지역_n'].value_counts()

0     1
13    1
23    1
22    1
21    1
20    1
19    1
18    1
17    1
16    1
15    1
14    1
12    1
1     1
11    1
10    1
9     1
8     1
7     1
6     1
5     1
4     1
3     1
2     1
24    1
Name: 지역_n, dtype: int64

In [20]:
#onehot encoding

In [17]:
df3['지역_hot'] = LabelEncoder().fit_transform(df2['지역'])

In [18]:
df3['지역_hot'].value_counts()

0     1
13    1
23    1
22    1
21    1
20    1
19    1
18    1
17    1
16    1
15    1
14    1
12    1
1     1
11    1
10    1
9     1
8     1
7     1
6     1
5     1
4     1
3     1
2     1
24    1
Name: 지역_hot, dtype: int64

In [19]:
onehot = pd.get_dummies(df3['지역_hot'])
onehot.columns = ['강남구', '강동구', '강북구', '강서구', '관악구', '광진구', '구로구', '금천구', '노원구',
       '도봉구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구',
       '양천구', '영등포구', '용산구', '은평구', '종로구', '중구', '중랑구']
onehot

,강남구,강동구,강북구,강서구,관악구,광진구,구로구,금천구,노원구,도봉구,...,성동구,성북구,송파구,양천구,영등포구,용산구,은평구,종로구,중구,중랑구
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
24,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1